config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cats

  root to: "cats#index"

  get 'pages/index'

  get 'pages/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  validates :name, :picture, presence: true

  validates :name, uniqueness: true

  mount_uploader :picture, AvatarUploader

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :age, :avatar, :email, :password, :password_confirmation])

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :age, :avatar, :email, :password, :password_confirmation])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :picture, :description, :age)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cats/_form.html.erb
<%= form_for(cat) do |f| %>
<% if cat.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(cat.errors.count, "error") %> prohibited this cat from being saved:</h2>
  <ul>
    <% cat.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="container">
    <div class="col-md-4 col-md-offset-4 form-group">
      <div class="well">
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control"%>
      </div>

      <div class="field">
        <%= f.label :age %>
        <%= f.text_field :age, id: :dog_age, class: "form-control"%>
      </div>

      <div class="field">
        <%= f.label :picture %>
        <%= f.file_field :picture, class: "form-control"%>
      </div>

      <div class="field">
        <%= f.label :description %>
        <%= f.text_area :description, class: "form-control" %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/cats/edit.html.erb
<h1 class="text-center">Editing Cat</h1>

<%= render 'form', cat: @cat %>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= link_to 'Show', @cat %> |
      <%= link_to 'Back', cats_path %>
    </div>
  </div>
</div>

app/views/cats/index.html.erb
<h1 class="text-center">Cats</h1>

<div class="container">
  <div class="row">
    <% @cats.each do |cat| %>
    <div class="col-md-4">
      <div class="well">
        <h3><%= cat.name %></h3>
        <%= image_tag cat.picture, class: "img-responsive" %>
        <blockquote>
          <%= cat.description %>
        </blockquote>
        <%= link_to 'Show', cat, class: "btn btn-primary" %>
        <%= link_to 'Edit', edit_cat_path(cat), class: "btn btn-success" %>
        <%= link_to 'Destroy', cat, class: "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/cats/new.html.erb
<h1 class="text-center">New Cat</h1>

<%= render 'form', cat: @cat %>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= link_to 'Back', cats_path %>
    </div>
  </div>
</div>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="well">
        <h4>Name: <%= @cat.name %></h4>
        <p>
          <strong>Picture:</strong>
          <%= image_tag @cat.picture, class: "img-responsive"%>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @cat.description %>
        </p>

        <p>
          <strong>Age:</strong>
          <%= @cat.age %>
        </p>
      </div>
      <%= link_to 'Edit', edit_cat_path(@cat) %> |
      <%= link_to 'Back', cats_path %>
    </div>
  </div>



</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Claserest</title>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>
  <% if user_signed_in?%>
  <%= render 'shared/navbar'%>
  <%end%>
  <% if notice%>
    <p class="notice text-center bg-success"><%= notice %></p>
  <%else%>
    <%if alert%>
    <p class="alert text-center bg-success"><%= alert %></p>
    <%end%>
  <%end%>
  <%= yield %>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand"><%=image_tag current_user.avatar, class: "inset"%></span>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <% if user_signed_in?%>
      <ul class="nav navbar-nav">
          <li><p>Bienvenid@! <%=current_user.name%></p></li>
        </ul>
        <% end %>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <span class="glyphicon glyphicon-user" aria-hidden="true"></span> Mi Cuenta
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% if user_signed_in?%>
            <li><%= link_to ' Home', cats_path, class:"glyphicon glyphicon-home"%></li>
            <li><%= link_to ' Agregar nuevo', new_cat_path, class:"glyphicon glyphicon-save"%></li>
            <li><%= link_to ' Editar Perfil', edit_user_registration_path, class:"glyphicon glyphicon-edit" %></li>
            <li><%= link_to ' Cerrar Sesión', destroy_user_session_path, method: :delete, class:"glyphicon glyphicon-off" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>